apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-ensemble-test
spec:
  parallelism: 5
  script:
    configMap:
      name: ensemble-browser-tests
      file: single-product-flow.js
  runner:
    resources:
      limits:
        cpu: "150m"
        memory: "250M"
      requests:
        cpu: "150m"
        memory: "250M"